# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c62888b3e8e5182a048c653d19c2811145a70fb958732e562f037a816e0e9fef05286317b7e143529b13a421f63e58bbcfb27d0fd42af81ddde8f49abafa6b2

test:
  secret_key_base: 88b5090cec7b40646ff2f3340d0ae044914a9ad3e1bd3c3cec4196c272e1ad07e15fd29958fdfefaf2126d7668e4dfcc685b6f429aaec5bfe21dd348fc928708

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
